### ISSUE TITLE
getting this error

### ISSUE THREAD

**Issue by stevenhines182** [DrakiaXYZ/SAIN#11]
Could not load [SAIN 2.1.7] because it has missing dependencies: com.spt-aki.core (v3.7.4 or newer)

i keep getting this error even though i have the current version of spt please help

**Comment by edudley909** [comment]
Same issued here:
Bepinex file, Amands Graphics is my only other mod. Used the SPT-AKI installer to install Version 3.7.5, on 12/19/2023

![Screenshot (4)](https://github.com/DrakiaXYZ/SAIN/assets/154387554/8e3cff38-46dc-43c5-8a51-87aafe1c5623)

**Comment by niklasschaeffer** [comment]
You guys are either using the wrong Aki-Version or you don't meet the required dependencys. The Version of Sain is for specific Aki-Versions. Your error above indicates you are missing the required Waypoints Mod in the correct Version.

Edit: Also read the mods description. There is stated Sain needs Waypoints and BigBrain.

**Comment by edudley909** [comment]
Dude, thanks for responding, I figured it out when I actually read the
page, derp! By the way, I fucking love this. I can finally play without
getting stomped every raid, I will probably never go back to the live
version, thank you guys so much, having a fucking blast.

**Comment by DrakiaXYZ** [comment]
@stevenhines182 This isn't an issue with SAIN. Either you've copied a `BepInEx/plugins/` folder from an old SPT install, or you're running a pirated copy of SPT.
