### ISSUE TITLE
Throwing Grenades seems to throw an exception

### ISSUE THREAD

**Issue by niklasschaeffer** [DrakiaXYZ/SAIN#12]
`2023-12-20 19:33:41.760 +01:00|0.13.5.3.26535|Error|Default|NullReferenceException: Object reference not set to an instance of an object
SAIN.SAINComponent.SubComponents.GrenadeTracker.EnemyGrenadeHeard () (at <35c5239657884ab3a86fb225943bdd4d>:0)
SAIN.SAINComponent.SubComponents.GrenadeTracker.Initialize (EFT.Grenade grenade, UnityEngine.Vector3 dangerPoint, System.Single reactionTime) (at <35c5239657884ab3a86fb225943bdd4d>:0)
SAIN.SAINComponent.Classes.SAINBotGrenadeClass.EnemyGrenadeThrown (EFT.Grenade grenade, UnityEngine.Vector3 dangerPoint) (at <35c5239657884ab3a86fb225943bdd4d>:0)
SAIN.Components.SAINBotControllerComponent.GrenadeThrown (EFT.Grenade grenade, UnityEngine.Vector3 position, UnityEngine.Vector3 force, System.Single mass) (at <35c5239657884ab3a86fb225943bdd4d>:0)
GClass520.ThrowGrenade (EFT.Grenade grenade, UnityEngine.Vector3 position, UnityEngine.Vector3 force, System.Single mass) (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
EFT.Player+BaseGrenadeController.vmethod_2 (System.Single timeSinceSafetyLevelRemoved, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.Vector3 force, System.Boolean lowThrow) (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
EFT.Player+BaseGrenadeController.method_7 (System.Single timeSinceSafetyLevelRemoved, System.Single lowHighThrow, UnityEngine.Vector3 direction, System.Single forcePower, System.Boolean lowThrow) (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
EFT.Player+BaseGrenadeController.vmethod_1 (System.Single timeSinceSafetyLevelRemoved, System.Boolean low) (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
EFT.Player+GrenadeController+Class953.method_2 (System.Boolean low) (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
EFT.Player+GrenadeController+Class953.OnDropGrenadeAction () (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
EFT.Player+BaseGrenadeController.method_2 () (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
EFT.Player+BaseGrenadeController.IEventsConsumerOnFiringBullet () (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
EFT.Player+AbstractHandsController.GInterface18.OnFiringBullet () (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
GClass584.smethod_9 (System.Collections.Generic.List`1[T] eventsConsumers, AnimationEventSystem.AnimationEventParameter parameter) (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
GClass584.AnimatorEventHandler (System.Collections.Generic.List`1[T] eventsConsumers, System.Int32 functionNameHash, AnimationEventSystem.AnimationEventParameter parameter) (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
ObjectInHandsAnimator.AnimatorEventHandler (System.Int32 functionNameHash, AnimationEventSystem.AnimationEventParameter parameter) (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
AnimationEventSystem.AnimationEventsEmitter.method_2 (System.String functionName, System.Int32 functionNameHash, AnimationEventSystem.AnimationEventParameter parameter, System.Int32 stateShortNameHash) (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
AnimationEventSystem.AnimationEventsEmitter.method_3 (AnimationEventSystem.AnimationEvent event, IAnimator animator, AnimatorStateInfoWrapper& stateInfo, System.Single normalizedTime) (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
AnimationEventSystem.AnimationEventsEmitter.EmitEvents () (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
EFT.Player+ItemHandsController.EmitEvents () (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
EFT.Player.method_68 (System.Single deltaTime) (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
EFT.Player.ComplexLateUpdate (EFT.EUpdateQueue queue, System.Single deltaTime) (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
(wrapper dynamic-method) EFT.Player.DMD<EFT.Player::LateUpdate>(EFT.Player)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
Class327:UnityEngine.ILogHandler.LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)`

**Comment by DrakiaXYZ** [comment]
Formatted:

```
2023-12-20 19:33:41.760 +01:00|0.13.5.3.26535|Error|Default|NullReferenceException: Object reference not set to an instance of an object
SAIN.SAINComponent.SubComponents.GrenadeTracker.EnemyGrenadeHeard () (at <35c5239657884ab3a86fb225943bdd4d>:0)
SAIN.SAINComponent.SubComponents.GrenadeTracker.Initialize (EFT.Grenade grenade, UnityEngine.Vector3 dangerPoint, System.Single reactionTime) (at <35c5239657884ab3a86fb225943bdd4d>:0)
SAIN.SAINComponent.Classes.SAINBotGrenadeClass.EnemyGrenadeThrown (EFT.Grenade grenade, UnityEngine.Vector3 dangerPoint) (at <35c5239657884ab3a86fb225943bdd4d>:0)
SAIN.Components.SAINBotControllerComponent.GrenadeThrown (EFT.Grenade grenade, UnityEngine.Vector3 position, UnityEngine.Vector3 force, System.Single mass) (at <35c5239657884ab3a86fb225943bdd4d>:0)
GClass520.ThrowGrenade (EFT.Grenade grenade, UnityEngine.Vector3 position, UnityEngine.Vector3 force, System.Single mass) (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
EFT.Player+BaseGrenadeController.vmethod_2 (System.Single timeSinceSafetyLevelRemoved, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, UnityEngine.Vector3 force, System.Boolean lowThrow) (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
EFT.Player+BaseGrenadeController.method_7 (System.Single timeSinceSafetyLevelRemoved, System.Single lowHighThrow, UnityEngine.Vector3 direction, System.Single forcePower, System.Boolean lowThrow) (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
EFT.Player+BaseGrenadeController.vmethod_1 (System.Single timeSinceSafetyLevelRemoved, System.Boolean low) (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
EFT.Player+GrenadeController+Class953.method_2 (System.Boolean low) (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
EFT.Player+GrenadeController+Class953.OnDropGrenadeAction () (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
EFT.Player+BaseGrenadeController.method_2 () (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
EFT.Player+BaseGrenadeController.IEventsConsumerOnFiringBullet () (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
EFT.Player+AbstractHandsController.GInterface18.OnFiringBullet () (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
GClass584.smethod_9 (System.Collections.Generic.List`1[T] eventsConsumers, AnimationEventSystem.AnimationEventParameter parameter) (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
GClass584.AnimatorEventHandler (System.Collections.Generic.List`1[T] eventsConsumers, System.Int32 functionNameHash, AnimationEventSystem.AnimationEventParameter parameter) (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
ObjectInHandsAnimator.AnimatorEventHandler (System.Int32 functionNameHash, AnimationEventSystem.AnimationEventParameter parameter) (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
AnimationEventSystem.AnimationEventsEmitter.method_2 (System.String functionName, System.Int32 functionNameHash, AnimationEventSystem.AnimationEventParameter parameter, System.Int32 stateShortNameHash) (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
AnimationEventSystem.AnimationEventsEmitter.method_3 (AnimationEventSystem.AnimationEvent event, IAnimator animator, AnimatorStateInfoWrapper& stateInfo, System.Single normalizedTime) (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
AnimationEventSystem.AnimationEventsEmitter.EmitEvents () (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
EFT.Player+ItemHandsController.EmitEvents () (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
EFT.Player.method_68 (System.Single deltaTime) (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
EFT.Player.ComplexLateUpdate (EFT.EUpdateQueue queue, System.Single deltaTime) (at <f7f3726f1deb4e1fabfff17fea715bfa>:0)
(wrapper dynamic-method) EFT.Player.DMD<EFT.Player::LateUpdate>(EFT.Player)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
Class327:UnityEngine.ILogHandler.LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
```

I'll look into this next time I work on a SAIN release

**Comment by DrakiaXYZ** [comment]
Should be fixed in next release
