### ISSUE TITLE
Missing dependancy

### ISSUE THREAD

**Issue by Vendrasc** [DrakiaXYZ/SAIN#13]
Loading server I have no issues, get in game and it says "[Error] : Could not load SAIN 2.1.7 because it has missing dependencies: com.spt-aki.core (v3.7.4 or newer)

**Comment by DrakiaXYZ** [comment]
You're either running an outdated SPT (SAIN is built for _specific_ versions of SPT, as outlined in the mod version page), copied a BepInEx/Plugins/ folder from an old SPT version, or are running a pirated copy of SPT.

Not a SAIN issue

**Comment by Vendrasc** [comment]
Thank you. It was my SPT version. Much appreciate you replying.
