### ISSUE TITLE
Hi, im new. Just started SPT today, trying the AI mod and get this error message. Sorry if I installed wrong.

### ISSUE THREAD

**Issue by Skytter21** [DrakiaXYZ/SAIN#19]
![Error](https://github.com/DrakiaXYZ/SAIN/assets/157480142/2d3be412-df6e-4bd9-9307-4f3db5d650d6)

**Comment by DrakiaXYZ** [comment]
You are missing the dependency plugins as explained on the mod description page. Closing as this isn't a bug
