### ISSUE TITLE
Unable to fire any weapon properly

### ISSUE THREAD

**Issue by KyleCyaN** [DrakiaXYZ/SAIN#24]
In semi-auto mode, several presses are required to fire a bullet...I don't know hot to fix.

![6b3dcc5081a56e8fa1280bfc561fe583](https://github.com/DrakiaXYZ/SAIN/assets/66722059/4e8bb802-7e1b-4913-a3d1-5d17cb569e42)

**Comment by DrakiaXYZ** [comment]
This is most likely caused by something crashing earlier in the raid. I would need the `Logs/log_[date]/[date] traces.log` and `BepInEx/LogOutput.log` files to diagnose
