### ISSUE TITLE
Bot blind fire accuracy setting

### ISSUE THREAD

**Issue by timf1256** [DrakiaXYZ/SAIN#26]
Not a bug but an enhancement request.  It would be nice if there were a setting to reduce bot blind fire accuracy or disable their ability to blind fire entirely.  Sometimes it feels like every bot I bump into sprints to cover and blind fires.  On lower difficulties they usually miss but only the first few shots, and then it seems like they adjust fire even though they can't see where they are shooting.  I've even been head, eyes'd a few times within 5 shots by a bot blind firing behind cover.  This is on the easier preset, one below default, with headshot protection on as default.  I haven't changed anything else, just switched the preset.

**Comment by DrakiaXYZ** [comment]
You'll want to post this on the main repo: https://github.com/Solarint/SAIN

Solarint has taken development over again, so he'll be the one looking at adding new features
